# Generated by Django 3.2.5 on 2021-08-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogform',
            old_name='content',
            new_name='Content',
        ),
        migrations.AddField(
            model_name='blogform',
            name='Image1',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
    ]
