# Generated by Django 3.2.5 on 2021-08-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_image1_blogform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogform',
            name='Image',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
    ]
