# Generated by Django 3.2.5 on 2021-08-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogform',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
