# Generated by Django 3.2.5 on 2021-08-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogform',
            name='Content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogform',
            name='Image',
            field=models.ImageField(null=True, upload_to='myimages'),
        ),
        migrations.AlterField(
            model_name='blogform',
            name='Title',
            field=models.CharField(max_length=255),
        ),
    ]
