# Generated by Django 3.2.5 on 2021-08-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210820_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogform',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='my_images'),
        ),
    ]
